./run.sh: line 2: /usr/local/bin/python3: No such file or directory
./run.sh: line 2: /usr/local/bin/python3: No such file or directory
Traceback (most recent call last):
  File "/home/abisgood/Documents/Coding/Financial-Tracker/src/./main.py", line 2, in <module>
    from ClientIO import ClientIO
  File "/home/abisgood/Documents/Coding/Financial-Tracker/src/ClientIO.py", line 3, in <module>
    from dotenv import load_dotenv, dotenv_values
ModuleNotFoundError: No module named 'dotenv'
Traceback (most recent call last):
  File "/home/abisgood/Documents/Coding/Financial-Tracker/src/./main.py", line 2, in <module>
    from ClientIO import ClientIO
  File "/home/abisgood/Documents/Coding/Financial-Tracker/src/ClientIO.py", line 3, in <module>
    from dotenv import load_dotenv, dotenv_values
ModuleNotFoundError: No module named 'dotenv'
2024-08-15 23:38:49.613595
createDB.py ran successfully
Error running addToDB.js
2024-08-15 23:39:53.430072
Error running addToDB.js
2024-08-15 23:41:33.286169
Error running addToDB.js
2024-10-13 16:44:20.380813
addToDB.js ran successfully
Opened database successfully
